// Auto-generated: contabilità Febbraio 2026 (sostituisce dati seed precedenti)
export const FEBRUARY_2026_MOVEMENTS = [
  {"id": "feb26-cassa-entrata-0", "date": "2026-02-15", "description": "AL CASTELLO", "category": "Generale", "paymentMethod": "B", "type": "entrata", "status": "cassa", "amount": 267.79},
  {"id": "feb26-cassa-entrata-1", "date": "2026-02-15", "description": "ALOVISI", "category": "Generale", "paymentMethod": "B", "type": "entrata", "status": "cassa", "amount": 3006.3},
  {"id": "feb26-cassa-entrata-2", "date": "2026-02-15", "description": "ARREDI DI QUARIERE", "category": "Generale", "paymentMethod": "B", "type": "entrata", "status": "cassa", "amount": 99.13},
  {"id": "feb26-cassa-entrata-3", "date": "2026-02-15", "description": "BE WATER", "category": "Generale", "paymentMethod": "B", "type": "entrata", "status": "cassa", "amount": 2562.0},
  {"id": "feb26-cassa-entrata-4", "date": "2026-02-15", "description": "BIM", "category": "Generale", "paymentMethod": "B", "type": "entrata", "status": "cassa", "amount": 300.12},
  {"id": "feb26-cassa-entrata-5", "date": "2026-02-15", "description": "BIM", "category": "Generale", "paymentMethod": "B", "type": "entrata", "status": "cassa", "amount": 745.42},
  {"id": "feb26-cassa-entrata-6", "date": "2026-02-15", "description": "CATS", "category": "Generale", "paymentMethod": "B", "type": "entrata", "status": "cassa", "amount": 124.1},
  {"id": "feb26-cassa-entrata-7", "date": "2026-02-15", "description": "COMUNE DI CASAGIOVE", "category": "Generale", "paymentMethod": "B", "type": "entrata", "status": "cassa", "amount": 4490.0},
  {"id": "feb26-cassa-entrata-8", "date": "2026-02-15", "description": "COMUNE DI CASAGIOVE", "category": "Generale", "paymentMethod": "B", "type": "entrata", "status": "cassa", "amount": 10500.0},
  {"id": "feb26-cassa-entrata-9", "date": "2026-02-15", "description": "COSTRUZIONI VITALE", "category": "Generale", "paymentMethod": "B", "type": "entrata", "status": "cassa", "amount": 1892.95},
  {"id": "feb26-cassa-entrata-10", "date": "2026-02-15", "description": "ELEA", "category": "Generale", "paymentMethod": "N", "type": "entrata", "status": "cassa", "amount": 48.0},
  {"id": "feb26-cassa-entrata-11", "date": "2026-02-15", "description": "EMABY", "category": "Generale", "paymentMethod": "B", "type": "entrata", "status": "cassa", "amount": 208.86},
  {"id": "feb26-cassa-entrata-12", "date": "2026-02-15", "description": "EMMEQUADRO", "category": "Generale", "paymentMethod": "B", "type": "entrata", "status": "cassa", "amount": 235.46},
  {"id": "feb26-cassa-entrata-13", "date": "2026-02-15", "description": "FANTATEATRO", "category": "Generale", "paymentMethod": "B", "type": "entrata", "status": "cassa", "amount": 2086.2},
  {"id": "feb26-cassa-entrata-14", "date": "2026-02-15", "description": "FERMAX", "category": "Generale", "paymentMethod": "B", "type": "entrata", "status": "cassa", "amount": 157.38},
  {"id": "feb26-cassa-entrata-15", "date": "2026-02-15", "description": "GIUSTINIANI", "category": "Generale", "paymentMethod": "B", "type": "entrata", "status": "cassa", "amount": 5622.98},
  {"id": "feb26-cassa-entrata-16", "date": "2026-02-15", "description": "GIUSTINIANI", "category": "Generale", "paymentMethod": "B", "type": "entrata", "status": "cassa", "amount": 1610.4},
  {"id": "feb26-cassa-entrata-17", "date": "2026-02-15", "description": "GIUSTINIANI 01/26", "category": "Generale", "paymentMethod": "B", "type": "entrata", "status": "cassa", "amount": 5636.57},
  {"id": "feb26-cassa-entrata-18", "date": "2026-02-15", "description": "INSCENA", "category": "Generale", "paymentMethod": "B", "type": "entrata", "status": "cassa", "amount": 1366.72},
  {"id": "feb26-cassa-entrata-19", "date": "2026-02-15", "description": "INSCENA", "category": "Generale", "paymentMethod": "B", "type": "entrata", "status": "cassa", "amount": 3181.15},
  {"id": "feb26-cassa-entrata-20", "date": "2026-02-15", "description": "L'ISOLA DANZA", "category": "Generale", "paymentMethod": "B", "type": "entrata", "status": "cassa", "amount": 561.2},
  {"id": "feb26-cassa-entrata-21", "date": "2026-02-15", "description": "MARPLAST", "category": "Generale", "paymentMethod": "N", "type": "entrata", "status": "cassa", "amount": 60.0},
  {"id": "feb26-cassa-entrata-22", "date": "2026-02-15", "description": "MASSIMO", "category": "Generale", "paymentMethod": "N", "type": "entrata", "status": "cassa", "amount": 7150.0},
  {"id": "feb26-cassa-entrata-23", "date": "2026-02-15", "description": "MERCADANTE", "category": "Generale", "paymentMethod": "B", "type": "entrata", "status": "cassa", "amount": 65.0},
  {"id": "feb26-cassa-entrata-24", "date": "2026-02-15", "description": "MERCADANTE", "category": "Generale", "paymentMethod": "B", "type": "entrata", "status": "cassa", "amount": 90.0},
  {"id": "feb26-cassa-entrata-25", "date": "2026-02-15", "description": "MERCADANTE", "category": "Generale", "paymentMethod": "B", "type": "entrata", "status": "cassa", "amount": 90.0},
  {"id": "feb26-cassa-entrata-26", "date": "2026-02-15", "description": "MI ESIBISCO", "category": "Generale", "paymentMethod": "B", "type": "entrata", "status": "cassa", "amount": 244.98},
  {"id": "feb26-cassa-entrata-27", "date": "2026-02-15", "description": "MULTIAX", "category": "Generale", "paymentMethod": "B", "type": "entrata", "status": "cassa", "amount": 195.2},
  {"id": "feb26-cassa-entrata-28", "date": "2026-02-15", "description": "NSS", "category": "Generale", "paymentMethod": "C", "type": "entrata", "status": "cassa", "amount": 137.86},
  {"id": "feb26-cassa-entrata-29", "date": "2026-02-15", "description": "NUOVO TEATRO", "category": "Generale", "paymentMethod": "B", "type": "entrata", "status": "cassa", "amount": 585.6},
  {"id": "feb26-cassa-entrata-30", "date": "2026-02-15", "description": "NUOVO TEATRO", "category": "Generale", "paymentMethod": "B", "type": "entrata", "status": "cassa", "amount": 176.9},
  {"id": "feb26-cassa-entrata-31", "date": "2026-02-15", "description": "NUOVO TEATRO", "category": "Generale", "paymentMethod": "B", "type": "entrata", "status": "cassa", "amount": 3904.0},
  {"id": "feb26-cassa-entrata-32", "date": "2026-02-15", "description": "PARATI VITTORIO", "category": "Generale", "paymentMethod": "B", "type": "entrata", "status": "cassa", "amount": 190.6},
  {"id": "feb26-cassa-entrata-33", "date": "2026-02-15", "description": "PERRELLA", "category": "Generale", "paymentMethod": "B", "type": "entrata", "status": "cassa", "amount": 1185.84},
  {"id": "feb26-cassa-entrata-34", "date": "2026-02-15", "description": "PERRELLA", "category": "Generale", "paymentMethod": "B", "type": "entrata", "status": "cassa", "amount": 167.09},
  {"id": "feb26-cassa-entrata-35", "date": "2026-02-15", "description": "PLEX", "category": "Generale", "paymentMethod": "N", "type": "entrata", "status": "cassa", "amount": 30.0},
  {"id": "feb26-cassa-entrata-36", "date": "2026-02-15", "description": "QUINTESSENZA", "category": "Generale", "paymentMethod": "C", "type": "entrata", "status": "cassa", "amount": 183.0},
  {"id": "feb26-cassa-entrata-37", "date": "2026-02-15", "description": "RAI", "category": "Generale", "paymentMethod": "C", "type": "entrata", "status": "cassa", "amount": 250.0},
  {"id": "feb26-cassa-entrata-38", "date": "2026-02-15", "description": "RAI (UPAS) 26/2", "category": "Generale", "paymentMethod": "B", "type": "entrata", "status": "cassa", "amount": 980.0},
  {"id": "feb26-cassa-entrata-39", "date": "2026-02-15", "description": "RAI 26/2", "category": "Generale", "paymentMethod": "B", "type": "entrata", "status": "cassa", "amount": 500.0},
  {"id": "feb26-cassa-entrata-40", "date": "2026-02-15", "description": "RAI 26/2", "category": "Generale", "paymentMethod": "B", "type": "entrata", "status": "cassa", "amount": 6200.0},
  {"id": "feb26-cassa-entrata-41", "date": "2026-02-15", "description": "RAI 26/2", "category": "Generale", "paymentMethod": "B", "type": "entrata", "status": "cassa", "amount": 29828.0},
  {"id": "feb26-cassa-entrata-42", "date": "2026-02-15", "description": "RAI 26/2", "category": "Generale", "paymentMethod": "B", "type": "entrata", "status": "cassa", "amount": 1900.0},
  {"id": "feb26-cassa-entrata-43", "date": "2026-02-15", "description": "RAI ALLEGRO 26/2", "category": "Generale", "paymentMethod": "B", "type": "entrata", "status": "cassa", "amount": 9494.5},
  {"id": "feb26-cassa-entrata-44", "date": "2026-02-15", "description": "RAI ALLEGRO 26/2", "category": "Generale", "paymentMethod": "B", "type": "entrata", "status": "cassa", "amount": 12196.0},
  {"id": "feb26-cassa-entrata-45", "date": "2026-02-15", "description": "RAI INTEGR 26/2", "category": "Generale", "paymentMethod": "B", "type": "entrata", "status": "cassa", "amount": 650.0},
  {"id": "feb26-cassa-entrata-46", "date": "2026-02-15", "description": "RAI PAL MOQ 26/2", "category": "Generale", "paymentMethod": "B", "type": "entrata", "status": "cassa", "amount": 11100.0},
  {"id": "feb26-cassa-entrata-47", "date": "2026-02-15", "description": "RAI PALIN 26/2", "category": "Generale", "paymentMethod": "B", "type": "entrata", "status": "cassa", "amount": 7140.0},
  {"id": "feb26-cassa-entrata-48", "date": "2026-02-15", "description": "RAI prix 25 26/2", "category": "Generale", "paymentMethod": "B", "type": "entrata", "status": "cassa", "amount": 6635.0},
  {"id": "feb26-cassa-entrata-49", "date": "2026-02-15", "description": "RAI prix 25 26/2", "category": "Generale", "paymentMethod": "B", "type": "entrata", "status": "cassa", "amount": 2040.0},
  {"id": "feb26-cassa-entrata-50", "date": "2026-02-15", "description": "REZINA", "category": "Generale", "paymentMethod": "B", "type": "entrata", "status": "cassa", "amount": 73.2},
  {"id": "feb26-cassa-entrata-51", "date": "2026-02-15", "description": "SALVATORE TELA SCENO", "category": "Generale", "paymentMethod": "N", "type": "entrata", "status": "cassa", "amount": 196.0},
  {"id": "feb26-cassa-entrata-52", "date": "2026-02-15", "description": "SALVATORE TELA SCENO", "category": "Generale", "paymentMethod": "N", "type": "entrata", "status": "cassa", "amount": 158.0},
  {"id": "feb26-cassa-entrata-53", "date": "2026-02-15", "description": "SAN CARLO", "category": "Generale", "paymentMethod": "B", "type": "entrata", "status": "cassa", "amount": 16555.0},
  {"id": "feb26-cassa-entrata-54", "date": "2026-02-15", "description": "SAN CARLO", "category": "Generale", "paymentMethod": "B", "type": "entrata", "status": "cassa", "amount": 9153.8},
  {"id": "feb26-cassa-entrata-55", "date": "2026-02-15", "description": "TEATRICOMIO", "category": "Generale", "paymentMethod": "C", "type": "entrata", "status": "cassa", "amount": 393.82},
  {"id": "feb26-cassa-entrata-56", "date": "2026-02-15", "description": "TEATRO CATANIA", "category": "Generale", "paymentMethod": "B", "type": "entrata", "status": "cassa", "amount": 2822.28},
  {"id": "feb26-cassa-entrata-57", "date": "2026-02-15", "description": "TEATRO DI ROMA", "category": "Generale", "paymentMethod": "B", "type": "entrata", "status": "cassa", "amount": 1765.0},
  {"id": "feb26-cassa-entrata-58", "date": "2026-02-15", "description": "TEATRO FRANCO PARENTI", "category": "Generale", "paymentMethod": "B", "type": "entrata", "status": "cassa", "amount": 1848.3},
  {"id": "feb26-cassa-entrata-59", "date": "2026-02-15", "description": "TEATRO SEGRETO", "category": "Generale", "paymentMethod": "B", "type": "entrata", "status": "cassa", "amount": 357.22},
  {"id": "feb26-cassa-entrata-60", "date": "2026-02-15", "description": "TEATRO TORINO", "category": "Generale", "paymentMethod": "B", "type": "entrata", "status": "cassa", "amount": 910.0},
  {"id": "feb26-cassa-entrata-61", "date": "2026-02-15", "description": "TELASTAMPO", "category": "Generale", "paymentMethod": "B", "type": "entrata", "status": "cassa", "amount": 396.45},
  {"id": "feb26-cassa-entrata-62", "date": "2026-02-15", "description": "THE JACKAL", "category": "Generale", "paymentMethod": "B", "type": "entrata", "status": "cassa", "amount": 366.0},
  {"id": "feb26-cassa-entrata-63", "date": "2026-02-15", "description": "UNO SPAZIO PER IL TEATRO", "category": "Generale", "paymentMethod": "C", "type": "entrata", "status": "cassa", "amount": 263.76},
  {"id": "feb26-cassa-entrata-64", "date": "2026-02-15", "description": "URBAN VALUE", "category": "Generale", "paymentMethod": "B", "type": "entrata", "status": "cassa", "amount": 2931.17},
  {"id": "feb26-cassa-entrata-65", "date": "2026-02-15", "description": "VITTORIO PAR", "category": "Generale", "paymentMethod": "N", "type": "entrata", "status": "cassa", "amount": 379.0},
  {"id": "feb26-cassa-entrata-66", "date": "2026-02-15", "description": "VITTORIO PAR", "category": "Generale", "paymentMethod": "N", "type": "entrata", "status": "cassa", "amount": 292.0},
  {"id": "feb26-cassa-entrata-67", "date": "2026-02-15", "description": "VITTORIO PAR", "category": "Generale", "paymentMethod": "N", "type": "entrata", "status": "cassa", "amount": 285.0},
  {"id": "feb26-cassa-entrata-68", "date": "2026-02-15", "description": "VITTORIO PAR", "category": "Generale", "paymentMethod": "N", "type": "entrata", "status": "cassa", "amount": 255.0},
  {"id": "feb26-cassa-entrata-69", "date": "2026-02-15", "description": "WILDSIDE", "category": "Generale", "paymentMethod": "C", "type": "entrata", "status": "cassa", "amount": 219.6},
  {"id": "feb26-cassa-entrata-70", "date": "2026-02-15", "description": "WILDSIDE", "category": "Generale", "paymentMethod": "B", "type": "entrata", "status": "cassa", "amount": 179.4},
  {"id": "feb26-cassa-entrata-71", "date": "2026-02-15", "description": "WILDSIDE", "category": "Generale", "paymentMethod": "B", "type": "entrata", "status": "cassa", "amount": 755.34},
  {"id": "feb26-cassa-uscita-0", "date": "2026-02-15", "description": "A&P", "category": "Generale", "paymentMethod": "B", "type": "uscita", "status": "cassa", "amount": 339.22},
  {"id": "feb26-cassa-uscita-1", "date": "2026-02-15", "description": "A&P", "category": "Generale", "paymentMethod": "B", "type": "uscita", "status": "cassa", "amount": 1747.1},
  {"id": "feb26-cassa-uscita-2", "date": "2026-02-15", "description": "ABTARE", "category": "Generale", "paymentMethod": "B", "type": "uscita", "status": "cassa", "amount": 8723.0},
  {"id": "feb26-cassa-uscita-3", "date": "2026-02-15", "description": "ACCONTO FELPE", "category": "Generale", "paymentMethod": "C", "type": "uscita", "status": "cassa", "amount": 100.0},
  {"id": "feb26-cassa-uscita-4", "date": "2026-02-15", "description": "AG ENTRATE", "category": "Generale", "paymentMethod": "F", "type": "uscita", "status": "cassa", "amount": 57.47},
  {"id": "feb26-cassa-uscita-5", "date": "2026-02-15", "description": "AGENZIA DELLE ENTRATE", "category": "Generale", "paymentMethod": "B", "type": "uscita", "status": "cassa", "amount": 7036.14},
  {"id": "feb26-cassa-uscita-6", "date": "2026-02-15", "description": "ALE", "category": "Generale", "paymentMethod": "N", "type": "uscita", "status": "cassa", "amount": 5000.0},
  {"id": "feb26-cassa-uscita-7", "date": "2026-02-15", "description": "ALLIANZ", "category": "Generale", "paymentMethod": "F", "type": "uscita", "status": "cassa", "amount": 50.2},
  {"id": "feb26-cassa-uscita-8", "date": "2026-02-15", "description": "ALMA", "category": "Generale", "paymentMethod": "B", "type": "uscita", "status": "cassa", "amount": 2934.1},
  {"id": "feb26-cassa-uscita-9", "date": "2026-02-15", "description": "APA", "category": "Generale", "paymentMethod": "R", "type": "uscita", "status": "cassa", "amount": 528.6},
  {"id": "feb26-cassa-uscita-10", "date": "2026-02-15", "description": "APA", "category": "Generale", "paymentMethod": "R", "type": "uscita", "status": "cassa", "amount": 1383.39},
  {"id": "feb26-cassa-uscita-11", "date": "2026-02-15", "description": "APA", "category": "Generale", "paymentMethod": "R", "type": "uscita", "status": "cassa", "amount": 1583.07},
  {"id": "feb26-cassa-uscita-12", "date": "2026-02-15", "description": "APA", "category": "Generale", "paymentMethod": "R", "type": "uscita", "status": "cassa", "amount": 1427.18},
  {"id": "feb26-cassa-uscita-13", "date": "2026-02-15", "description": "ARCO", "category": "Generale", "paymentMethod": "R", "type": "uscita", "status": "cassa", "amount": 385.67},
  {"id": "feb26-cassa-uscita-14", "date": "2026-02-15", "description": "ARCO", "category": "Generale", "paymentMethod": "R", "type": "uscita", "status": "cassa", "amount": 330.71},
  {"id": "feb26-cassa-uscita-15", "date": "2026-02-15", "description": "ASANA", "category": "Generale", "paymentMethod": "F", "type": "uscita", "status": "cassa", "amount": 164.58},
  {"id": "feb26-cassa-uscita-16", "date": "2026-02-15", "description": "BANCA", "category": "Generale", "paymentMethod": "F", "type": "uscita", "status": "cassa", "amount": 65.03},
  {"id": "feb26-cassa-uscita-17", "date": "2026-02-15", "description": "BANCA IFIS", "category": "Generale", "paymentMethod": "F", "type": "uscita", "status": "cassa", "amount": 991.01},
  {"id": "feb26-cassa-uscita-18", "date": "2026-02-15", "description": "BANCA IFIS", "category": "Generale", "paymentMethod": "F", "type": "uscita", "status": "cassa", "amount": 331.66},
  {"id": "feb26-cassa-uscita-19", "date": "2026-02-15", "description": "BENZINA", "category": "Generale", "paymentMethod": "CC", "type": "uscita", "status": "cassa", "amount": 310.0},
  {"id": "feb26-cassa-uscita-20", "date": "2026-02-15", "description": "BENZINA+TANG", "category": "Generale", "paymentMethod": "N", "type": "uscita", "status": "cassa", "amount": 23.5},
  {"id": "feb26-cassa-uscita-21", "date": "2026-02-15", "description": "BNL", "category": "Generale", "paymentMethod": "F", "type": "uscita", "status": "cassa", "amount": 46.85},
  {"id": "feb26-cassa-uscita-22", "date": "2026-02-15", "description": "BOCCASCENA", "category": "Generale", "paymentMethod": "B", "type": "uscita", "status": "cassa", "amount": 2648.38},
  {"id": "feb26-cassa-uscita-23", "date": "2026-02-15", "description": "CAST INFO", "category": "Generale", "paymentMethod": "B", "type": "uscita", "status": "cassa", "amount": 3550.52},
  {"id": "feb26-cassa-uscita-24", "date": "2026-02-15", "description": "CIFEM", "category": "Generale", "paymentMethod": "CC", "type": "uscita", "status": "cassa", "amount": 19.0},
  {"id": "feb26-cassa-uscita-25", "date": "2026-02-15", "description": "CINESE", "category": "Generale", "paymentMethod": "N", "type": "uscita", "status": "cassa", "amount": 16.7},
  {"id": "feb26-cassa-uscita-26", "date": "2026-02-15", "description": "CMG", "category": "Generale", "paymentMethod": "B", "type": "uscita", "status": "cassa", "amount": 367.0},
  {"id": "feb26-cassa-uscita-27", "date": "2026-02-15", "description": "CONDOMINIO", "category": "Generale", "paymentMethod": "F", "type": "uscita", "status": "cassa", "amount": 264.0},
  {"id": "feb26-cassa-uscita-28", "date": "2026-02-15", "description": "CUTTING", "category": "Generale", "paymentMethod": "B", "type": "uscita", "status": "cassa", "amount": 1205.36},
  {"id": "feb26-cassa-uscita-29", "date": "2026-02-15", "description": "DALENA", "category": "Generale", "paymentMethod": "B", "type": "uscita", "status": "cassa", "amount": 207.4},
  {"id": "feb26-cassa-uscita-30", "date": "2026-02-15", "description": "DE ANGELIS", "category": "Generale", "paymentMethod": "F", "type": "uscita", "status": "cassa", "amount": 2101.33},
  {"id": "feb26-cassa-uscita-31", "date": "2026-02-15", "description": "DE LAGE", "category": "Generale", "paymentMethod": "F", "type": "uscita", "status": "cassa", "amount": 3722.31},
  {"id": "feb26-cassa-uscita-32", "date": "2026-02-15", "description": "DECORA", "category": "Generale", "paymentMethod": "B", "type": "uscita", "status": "cassa", "amount": 90.0},
  {"id": "feb26-cassa-uscita-33", "date": "2026-02-15", "description": "DECORA", "category": "Generale", "paymentMethod": "CC", "type": "uscita", "status": "cassa", "amount": 19.19},
  {"id": "feb26-cassa-uscita-34", "date": "2026-02-15", "description": "DELTA", "category": "Generale", "paymentMethod": "CC", "type": "uscita", "status": "cassa", "amount": 25.0},
  {"id": "feb26-cassa-uscita-35", "date": "2026-02-15", "description": "DISCARICA", "category": "Generale", "paymentMethod": "N", "type": "uscita", "status": "cassa", "amount": 20.0},
  {"id": "feb26-cassa-uscita-36", "date": "2026-02-15", "description": "EGO", "category": "Generale", "paymentMethod": "CC", "type": "uscita", "status": "cassa", "amount": 2217.02},
  {"id": "feb26-cassa-uscita-37", "date": "2026-02-15", "description": "F24", "category": "Generale", "paymentMethod": "B", "type": "uscita", "status": "cassa", "amount": 453.0},
  {"id": "feb26-cassa-uscita-38", "date": "2026-02-15", "description": "F24 sansione", "category": "Generale", "paymentMethod": "B", "type": "uscita", "status": "cassa", "amount": 55.56},
  {"id": "feb26-cassa-uscita-39", "date": "2026-02-15", "description": "FABIO", "category": "Generale", "paymentMethod": "N", "type": "uscita", "status": "cassa", "amount": 203.0},
  {"id": "feb26-cassa-uscita-40", "date": "2026-02-15", "description": "FALEGNAME", "category": "Generale", "paymentMethod": "B", "type": "uscita", "status": "cassa", "amount": 800.0},
  {"id": "feb26-cassa-uscita-41", "date": "2026-02-15", "description": "FASTWEB", "category": "Generale", "paymentMethod": "F", "type": "uscita", "status": "cassa", "amount": 48.8},
  {"id": "feb26-cassa-uscita-42", "date": "2026-02-15", "description": "FEDEX", "category": "Generale", "paymentMethod": "R", "type": "uscita", "status": "cassa", "amount": 366.35},
  {"id": "feb26-cassa-uscita-43", "date": "2026-02-15", "description": "FERRAMENTA", "category": "Generale", "paymentMethod": "C", "type": "uscita", "status": "cassa", "amount": 5.0},
  {"id": "feb26-cassa-uscita-44", "date": "2026-02-15", "description": "FITTO", "category": "Generale", "paymentMethod": "F", "type": "uscita", "status": "cassa", "amount": 3000.0},
  {"id": "feb26-cassa-uscita-45", "date": "2026-02-15", "description": "FP", "category": "Generale", "paymentMethod": "C", "type": "uscita", "status": "cassa", "amount": 500.0},
  {"id": "feb26-cassa-uscita-46", "date": "2026-02-15", "description": "FP", "category": "Generale", "paymentMethod": "N", "type": "uscita", "status": "cassa", "amount": 1000.0},
  {"id": "feb26-cassa-uscita-47", "date": "2026-02-15", "description": "GEMAL", "category": "Generale", "paymentMethod": "F", "type": "uscita", "status": "cassa", "amount": 19.45},
  {"id": "feb26-cassa-uscita-48", "date": "2026-02-15", "description": "GEMAL", "category": "Generale", "paymentMethod": "F", "type": "uscita", "status": "cassa", "amount": 30.39},
  {"id": "feb26-cassa-uscita-49", "date": "2026-02-15", "description": "GEMAL", "category": "Generale", "paymentMethod": "F", "type": "uscita", "status": "cassa", "amount": 47.2},
  {"id": "feb26-cassa-uscita-50", "date": "2026-02-15", "description": "GIANLUIGI", "category": "Generale", "paymentMethod": "C", "type": "uscita", "status": "cassa", "amount": 100.0},
  {"id": "feb26-cassa-uscita-51", "date": "2026-02-15", "description": "GIANLUIGI", "category": "Generale", "paymentMethod": "N", "type": "uscita", "status": "cassa", "amount": 60.0},
  {"id": "feb26-cassa-uscita-52", "date": "2026-02-15", "description": "GRABO", "category": "Generale", "paymentMethod": "B", "type": "uscita", "status": "cassa", "amount": 7175.8},
  {"id": "feb26-cassa-uscita-53", "date": "2026-02-15", "description": "GRABO", "category": "Generale", "paymentMethod": "B", "type": "uscita", "status": "cassa", "amount": 13842.2},
  {"id": "feb26-cassa-uscita-54", "date": "2026-02-15", "description": "IBENA", "category": "Generale", "paymentMethod": "B", "type": "uscita", "status": "cassa", "amount": 1360.3},
  {"id": "feb26-cassa-uscita-55", "date": "2026-02-15", "description": "IFIS", "category": "Generale", "paymentMethod": "F", "type": "uscita", "status": "cassa", "amount": 150.76},
  {"id": "feb26-cassa-uscita-56", "date": "2026-02-15", "description": "LAMPADINA", "category": "Generale", "paymentMethod": "N", "type": "uscita", "status": "cassa", "amount": 2.0},
  {"id": "feb26-cassa-uscita-57", "date": "2026-02-15", "description": "LE MARK", "category": "Generale", "paymentMethod": "B", "type": "uscita", "status": "cassa", "amount": 1576.44},
  {"id": "feb26-cassa-uscita-58", "date": "2026-02-15", "description": "LEASYS", "category": "Generale", "paymentMethod": "F", "type": "uscita", "status": "cassa", "amount": 493.67},
  {"id": "feb26-cassa-uscita-59", "date": "2026-02-15", "description": "LEASYS", "category": "Generale", "paymentMethod": "F", "type": "uscita", "status": "cassa", "amount": 27.0},
  {"id": "feb26-cassa-uscita-60", "date": "2026-02-15", "description": "LEROY MERLIN", "category": "Generale", "paymentMethod": "B", "type": "uscita", "status": "cassa", "amount": 382.8},
  {"id": "feb26-cassa-uscita-61", "date": "2026-02-15", "description": "LEROY MERLIN", "category": "Generale", "paymentMethod": "CC", "type": "uscita", "status": "cassa", "amount": 97.43},
  {"id": "feb26-cassa-uscita-62", "date": "2026-02-15", "description": "LEROY MERLIN", "category": "Generale", "paymentMethod": "B", "type": "uscita", "status": "cassa", "amount": 55.94},
  {"id": "feb26-cassa-uscita-63", "date": "2026-02-15", "description": "LEROY MERLIN", "category": "Generale", "paymentMethod": "B", "type": "uscita", "status": "cassa", "amount": 47.94},
  {"id": "feb26-cassa-uscita-64", "date": "2026-02-15", "description": "lidl", "category": "Generale", "paymentMethod": "B", "type": "uscita", "status": "cassa", "amount": 39.98},
  {"id": "feb26-cassa-uscita-65", "date": "2026-02-15", "description": "lidl", "category": "Generale", "paymentMethod": "CC", "type": "uscita", "status": "cassa", "amount": 49.0},
  {"id": "feb26-cassa-uscita-66", "date": "2026-02-15", "description": "LIDL", "category": "Generale", "paymentMethod": "CC", "type": "uscita", "status": "cassa", "amount": 27.95},
  {"id": "feb26-cassa-uscita-67", "date": "2026-02-15", "description": "LINOLEUM GR", "category": "Generale", "paymentMethod": "B", "type": "uscita", "status": "cassa", "amount": 2936.05},
  {"id": "feb26-cassa-uscita-68", "date": "2026-02-15", "description": "MONDOCARTA", "category": "Generale", "paymentMethod": "C", "type": "uscita", "status": "cassa", "amount": 36.6},
  {"id": "feb26-cassa-uscita-69", "date": "2026-02-15", "description": "MUTUO II", "category": "Generale", "paymentMethod": "F", "type": "uscita", "status": "cassa", "amount": 633.0},
  {"id": "feb26-cassa-uscita-70", "date": "2026-02-15", "description": "MUTUO III", "category": "Generale", "paymentMethod": "F", "type": "uscita", "status": "cassa", "amount": 1693.5},
  {"id": "feb26-cassa-uscita-71", "date": "2026-02-15", "description": "NWG", "category": "Generale", "paymentMethod": "F", "type": "uscita", "status": "cassa", "amount": 1283.15},
  {"id": "feb26-cassa-uscita-72", "date": "2026-02-15", "description": "OXSIV", "category": "Generale", "paymentMethod": "B", "type": "uscita", "status": "cassa", "amount": 922.84},
  {"id": "feb26-cassa-uscita-73", "date": "2026-02-15", "description": "PARZIALE", "category": "Generale", "paymentMethod": "CC", "type": "uscita", "status": "cassa", "amount": 75.2},
  {"id": "feb26-cassa-uscita-74", "date": "2026-02-15", "description": "PAYPAL", "category": "Generale", "paymentMethod": "B", "type": "uscita", "status": "cassa", "amount": 591.45},
  {"id": "feb26-cassa-uscita-75", "date": "2026-02-15", "description": "PAYPAL", "category": "Generale", "paymentMethod": "B", "type": "uscita", "status": "cassa", "amount": 27.45},
  {"id": "feb26-cassa-uscita-76", "date": "2026-02-15", "description": "PIZZA PEPPE", "category": "Generale", "paymentMethod": "N", "type": "uscita", "status": "cassa", "amount": 6.5},
  {"id": "feb26-cassa-uscita-77", "date": "2026-02-15", "description": "PIZZE RAI", "category": "Generale", "paymentMethod": "N", "type": "uscita", "status": "cassa", "amount": 35.0},
  {"id": "feb26-cassa-uscita-78", "date": "2026-02-15", "description": "PLASTIDEA", "category": "Generale", "paymentMethod": "R", "type": "uscita", "status": "cassa", "amount": 479.07},
  {"id": "feb26-cassa-uscita-79", "date": "2026-02-15", "description": "PLASTIDEA", "category": "Generale", "paymentMethod": "R", "type": "uscita", "status": "cassa", "amount": 238.97},
  {"id": "feb26-cassa-uscita-80", "date": "2026-02-15", "description": "PONGS", "category": "Generale", "paymentMethod": "b", "type": "uscita", "status": "cassa", "amount": 885.0},
  {"id": "feb26-cassa-uscita-81", "date": "2026-02-15", "description": "POZIELLO", "category": "Generale", "paymentMethod": "R", "type": "uscita", "status": "cassa", "amount": 1019.59},
  {"id": "feb26-cassa-uscita-82", "date": "2026-02-15", "description": "POZIELLO", "category": "Generale", "paymentMethod": "R", "type": "uscita", "status": "cassa", "amount": 348.56},
  {"id": "feb26-cassa-uscita-83", "date": "2026-02-15", "description": "POZIELLO", "category": "Generale", "paymentMethod": "R", "type": "uscita", "status": "cassa", "amount": 499.64},
  {"id": "feb26-cassa-uscita-84", "date": "2026-02-15", "description": "RICCARDI", "category": "Generale", "paymentMethod": "B", "type": "uscita", "status": "cassa", "amount": 87.27},
  {"id": "feb26-cassa-uscita-85", "date": "2026-02-15", "description": "RISORGENTE", "category": "Generale", "paymentMethod": "B", "type": "uscita", "status": "cassa", "amount": 730.59},
  {"id": "feb26-cassa-uscita-86", "date": "2026-02-15", "description": "ROSETO", "category": "Generale", "paymentMethod": "B", "type": "uscita", "status": "cassa", "amount": 1500.0},
  {"id": "feb26-cassa-uscita-87", "date": "2026-02-15", "description": "SCHENKER", "category": "Generale", "paymentMethod": "R", "type": "uscita", "status": "cassa", "amount": 461.16},
  {"id": "feb26-cassa-uscita-88", "date": "2026-02-15", "description": "SCHENKER", "category": "Generale", "paymentMethod": "R", "type": "uscita", "status": "cassa", "amount": 348.0},
  {"id": "feb26-cassa-uscita-89", "date": "2026-02-15", "description": "SETEX", "category": "Generale", "paymentMethod": "B", "type": "uscita", "status": "cassa", "amount": 95.2},
  {"id": "feb26-cassa-uscita-90", "date": "2026-02-15", "description": "SHUTTERSTOCK", "category": "Generale", "paymentMethod": "F", "type": "uscita", "status": "cassa", "amount": 59.0},
  {"id": "feb26-cassa-uscita-91", "date": "2026-02-15", "description": "SHUTTERSTOCK", "category": "Generale", "paymentMethod": "F", "type": "uscita", "status": "cassa", "amount": 29.0},
  {"id": "feb26-cassa-uscita-92", "date": "2026-02-15", "description": "SPANDEX", "category": "Generale", "paymentMethod": "R", "type": "uscita", "status": "cassa", "amount": 1093.9},
  {"id": "feb26-cassa-uscita-93", "date": "2026-02-15", "description": "SPANDEX", "category": "Generale", "paymentMethod": "R", "type": "uscita", "status": "cassa", "amount": 299.19},
  {"id": "feb26-cassa-uscita-94", "date": "2026-02-15", "description": "SPANDEX", "category": "Generale", "paymentMethod": "R", "type": "uscita", "status": "cassa", "amount": 135.32},
  {"id": "feb26-cassa-uscita-95", "date": "2026-02-15", "description": "SPANDEX", "category": "Generale", "paymentMethod": "R", "type": "uscita", "status": "cassa", "amount": 605.02},
  {"id": "feb26-cassa-uscita-96", "date": "2026-02-15", "description": "SPANDEX", "category": "Generale", "paymentMethod": "R", "type": "uscita", "status": "cassa", "amount": 523.76},
  {"id": "feb26-cassa-uscita-97", "date": "2026-02-15", "description": "SPANDEX", "category": "Generale", "paymentMethod": "R", "type": "uscita", "status": "cassa", "amount": 1017.83},
  {"id": "feb26-cassa-uscita-98", "date": "2026-02-15", "description": "SPANDEX", "category": "Generale", "paymentMethod": "R", "type": "uscita", "status": "cassa", "amount": 131.27},
  {"id": "feb26-cassa-uscita-99", "date": "2026-02-15", "description": "SPANDEX", "category": "Generale", "paymentMethod": "R", "type": "uscita", "status": "cassa", "amount": 64.81},
  {"id": "feb26-cassa-uscita-100", "date": "2026-02-15", "description": "SPANDEX", "category": "Generale", "paymentMethod": "R", "type": "uscita", "status": "cassa", "amount": 1053.24},
  {"id": "feb26-cassa-uscita-101", "date": "2026-02-15", "description": "SPANDEX", "category": "Generale", "paymentMethod": "R", "type": "uscita", "status": "cassa", "amount": 203.77},
  {"id": "feb26-cassa-uscita-102", "date": "2026-02-15", "description": "SPANDEX", "category": "Generale", "paymentMethod": "R", "type": "uscita", "status": "cassa", "amount": 61.96},
  {"id": "feb26-cassa-uscita-103", "date": "2026-02-15", "description": "SPRIO", "category": "Generale", "paymentMethod": "B", "type": "uscita", "status": "cassa", "amount": 737.47},
  {"id": "feb26-cassa-uscita-104", "date": "2026-02-15", "description": "STELLANTIS", "category": "Generale", "paymentMethod": "F", "type": "uscita", "status": "cassa", "amount": 686.09},
  {"id": "feb26-cassa-uscita-105", "date": "2026-02-15", "description": "STIGLIANO", "category": "Generale", "paymentMethod": "B", "type": "uscita", "status": "cassa", "amount": 101.0},
  {"id": "feb26-cassa-uscita-106", "date": "2026-02-15", "description": "TEPEDE", "category": "Generale", "paymentMethod": "B", "type": "uscita", "status": "cassa", "amount": 1294.9},
  {"id": "feb26-cassa-uscita-107", "date": "2026-02-15", "description": "TNT", "category": "Generale", "paymentMethod": "R", "type": "uscita", "status": "cassa", "amount": 770.61},
  {"id": "feb26-cassa-uscita-108", "date": "2026-02-15", "description": "TNT", "category": "Generale", "paymentMethod": "R", "type": "uscita", "status": "cassa", "amount": 146.44},
  {"id": "feb26-cassa-uscita-109", "date": "2026-02-15", "description": "TREND", "category": "Generale", "paymentMethod": "R", "type": "uscita", "status": "cassa", "amount": 594.51},
  {"id": "feb26-cassa-uscita-110", "date": "2026-02-15", "description": "VATIERO", "category": "Generale", "paymentMethod": "B", "type": "uscita", "status": "cassa", "amount": 195.2},
  {"id": "feb26-cassa-uscita-111", "date": "2026-02-15", "description": "VATIERO", "category": "Generale", "paymentMethod": "B", "type": "uscita", "status": "cassa", "amount": 3733.2},
  {"id": "feb26-cassa-uscita-112", "date": "2026-02-15", "description": "VIACARD", "category": "Generale", "paymentMethod": "B", "type": "uscita", "status": "cassa", "amount": 123.06},
  {"id": "feb26-cassa-uscita-113", "date": "2026-02-15", "description": "VIDEOREGISTRATORE", "category": "Generale", "paymentMethod": "C", "type": "uscita", "status": "cassa", "amount": 30.0},
  {"id": "feb26-cassa-uscita-114", "date": "2026-02-15", "description": "VITALE", "category": "Generale", "paymentMethod": "N", "type": "uscita", "status": "cassa", "amount": 15.0},
  {"id": "feb26-cassa-uscita-115", "date": "2026-02-15", "description": "VITOLO", "category": "Generale", "paymentMethod": "C", "type": "uscita", "status": "cassa", "amount": 14.0},
  {"id": "feb26-cassa-uscita-116", "date": "2026-02-15", "description": "VITOLO", "category": "Generale", "paymentMethod": "B", "type": "uscita", "status": "cassa", "amount": 25.38},
  {"id": "feb26-cassa-uscita-117", "date": "2026-02-15", "description": "VITOLO", "category": "Generale", "paymentMethod": "B", "type": "uscita", "status": "cassa", "amount": 179.83},
  {"id": "feb26-cassa-uscita-118", "date": "2026-02-15", "description": "VITOLO", "category": "Generale", "paymentMethod": "B", "type": "uscita", "status": "cassa", "amount": 53.8},
  {"id": "feb26-cassa-uscita-119", "date": "2026-02-15", "description": "WESTHOLT", "category": "Generale", "paymentMethod": "B", "type": "uscita", "status": "cassa", "amount": 4318.0}
];
